-- Initial schema for the journal/publication platform backend.
--
-- IMPORTANT: this migration was authored by hand, not generated by
-- `prisma migrate dev`, because this sandbox's network policy blocks the
-- Prisma engine binary download (binaries.prisma.sh is not on the
-- allowlist) — there was no way to run Prisma against a real Postgres
-- instance here. It was written to match prisma/schema.prisma as closely
-- as `prisma migrate dev` would generate, but treat it as unverified
-- until you run `npx prisma migrate dev` yourself against a real
-- database — Prisma will either confirm it matches schema.prisma (no
-- drift) or generate a corrective migration if anything is off.

-- ── Extensions ──────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS vector;

-- ── Enums ───────────────────────────────────────────────────────────────

CREATE TYPE "ActiveArchivedStatus" AS ENUM ('active', 'archived');
CREATE TYPE "IssueStatus" AS ENUM ('published', 'current', 'archived');
CREATE TYPE "ArticleStatus" AS ENUM (
  'draft', 'submitted', 'under_review', 'revision_required', 'resubmitted',
  'accepted', 'rejected', 'scheduled', 'published', 'archived'
);
CREATE TYPE "EditorRole" AS ENUM (
  'editor_in_chief', 'managing_editor', 'associate_editor',
  'section_editor', 'board_member', 'guest_editor'
);
CREATE TYPE "EditorStatus" AS ENUM ('active', 'inactive');
CREATE TYPE "ReviewerStatus" AS ENUM ('active', 'inactive');
CREATE TYPE "ReviewRecommendation" AS ENUM ('accept', 'minor_revision', 'major_revision', 'reject');
CREATE TYPE "IndexingStatus" AS ENUM ('unconfirmed', 'confirmed', 'inactive');
CREATE TYPE "ContactMessageStatus" AS ENUM ('new', 'read', 'in_progress', 'resolved', 'archived');
CREATE TYPE "UserRole" AS ENUM (
  'super_admin', 'admin', 'editorial_subadmin', 'publication_subadmin',
  'seo_subadmin', 'support_subadmin', 'reviewer'
);

-- ── publishers ──────────────────────────────────────────────────────────

CREATE TABLE "publishers" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "logo" TEXT,
  "address" TEXT,
  "country" TEXT,
  "website" TEXT,
  "email" TEXT,
  "phone" TEXT,
  "status" "ActiveArchivedStatus" NOT NULL,
  "seo_title" TEXT,
  "seo_description" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "publishers_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "publishers_slug_key" ON "publishers"("slug");

-- ── publications ────────────────────────────────────────────────────────

CREATE TABLE "publications" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "publisher_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "short_name" TEXT NOT NULL,
  "tagline" TEXT,
  "issn_online" TEXT,
  "issn_print" TEXT,
  "founded" TEXT,
  "frequency" TEXT,
  "language" TEXT,
  "country" TEXT,
  "review_model" TEXT,
  "access_model" TEXT,
  "subject_area_ids" TEXT[],
  "email" TEXT,
  "address" TEXT,
  "website" TEXT,
  "logo" TEXT,
  "cover" TEXT,
  "status" "ActiveArchivedStatus" NOT NULL,
  "seo_title" TEXT,
  "seo_description" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "publications_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "publications_slug_key" ON "publications"("slug");
CREATE INDEX "publications_publisher_id_idx" ON "publications"("publisher_id");
ALTER TABLE "publications" ADD CONSTRAINT "publications_publisher_id_fkey"
  FOREIGN KEY ("publisher_id") REFERENCES "publishers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── volumes ─────────────────────────────────────────────────────────────

CREATE TABLE "volumes" (
  "id" TEXT NOT NULL,
  "publication_id" TEXT NOT NULL,
  "number" INTEGER NOT NULL,
  "year" INTEGER,
  "description" TEXT,
  "status" "ActiveArchivedStatus" NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "volumes_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "volumes_publication_id_number_key" ON "volumes"("publication_id", "number");
ALTER TABLE "volumes" ADD CONSTRAINT "volumes_publication_id_fkey"
  FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── issues ──────────────────────────────────────────────────────────────

CREATE TABLE "issues" (
  "id" TEXT NOT NULL,
  "volume_id" TEXT NOT NULL,
  "publication_id" TEXT NOT NULL,
  "number" INTEGER NOT NULL,
  "label" TEXT NOT NULL,
  "period" TEXT,
  "publication_date" DATE,
  "description" TEXT,
  "cover" TEXT,
  "status" "IssueStatus" NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "issues_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "issues_publication_id_idx" ON "issues"("publication_id");
CREATE INDEX "issues_volume_id_idx" ON "issues"("volume_id");
ALTER TABLE "issues" ADD CONSTRAINT "issues_volume_id_fkey"
  FOREIGN KEY ("volume_id") REFERENCES "volumes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "issues" ADD CONSTRAINT "issues_publication_id_fkey"
  FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- DATABASE_SCHEMA.md: "at most one Issue per publication_id may have
-- status = 'current'". Prisma can't express a partial unique index
-- declaratively (hence this hand-added block) — this is the hard
-- database-level backstop behind the application-level demotion logic in
-- src/modules/issues/issues.service.ts.
CREATE UNIQUE INDEX "issues_one_current_per_publication"
  ON "issues"("publication_id")
  WHERE "status" = 'current';

-- ── authors ─────────────────────────────────────────────────────────────

CREATE TABLE "authors" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "full_name" TEXT NOT NULL,
  "institution" TEXT,
  "department" TEXT,
  "country" TEXT,
  "bio" TEXT,
  "orcid" TEXT,
  "profile_image" TEXT,
  "website" TEXT,
  "email" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "authors_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "authors_slug_key" ON "authors"("slug");

-- ── articles ────────────────────────────────────────────────────────────

CREATE TABLE "articles" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "abstract" TEXT NOT NULL,
  "content" TEXT,
  "publication_id" TEXT NOT NULL,
  "volume_id" TEXT,
  "issue_id" TEXT,
  "pages" TEXT,
  "doi" TEXT,
  "manuscript_id" TEXT,
  "article_type" TEXT NOT NULL,
  "received_date" DATE,
  "revised_date" DATE,
  "accepted_date" DATE,
  "published_date" DATE,
  "pdf_url" TEXT,
  "supplementary_files" TEXT[],
  "references" TEXT[],
  "license" TEXT,
  "status" "ArticleStatus" NOT NULL,
  "area" TEXT,
  "seo_title" TEXT,
  "seo_description" TEXT,
  "seo_canonical_url" TEXT,
  "search_vector" tsvector,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "articles_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "articles_slug_key" ON "articles"("slug");
CREATE INDEX "articles_publication_id_idx" ON "articles"("publication_id");
CREATE INDEX "articles_status_idx" ON "articles"("status");
CREATE INDEX "articles_volume_id_idx" ON "articles"("volume_id");
CREATE INDEX "articles_issue_id_idx" ON "articles"("issue_id");
ALTER TABLE "articles" ADD CONSTRAINT "articles_publication_id_fkey"
  FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "articles" ADD CONSTRAINT "articles_volume_id_fkey"
  FOREIGN KEY ("volume_id") REFERENCES "volumes"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "articles" ADD CONSTRAINT "articles_issue_id_fkey"
  FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Full-text search (see src/modules/search/search.service.ts): keep
-- search_vector current on every insert/update via trigger, then index it.
CREATE FUNCTION articles_search_vector_update() RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.abstract, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.area, '')), 'C');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER articles_search_vector_trigger
  BEFORE INSERT OR UPDATE OF title, abstract, area ON "articles"
  FOR EACH ROW EXECUTE FUNCTION articles_search_vector_update();

CREATE INDEX "articles_search_vector_idx" ON "articles" USING GIN ("search_vector");

-- ── article_authors (join table, ordered) ──────────────────────────────

CREATE TABLE "article_authors" (
  "article_id" TEXT NOT NULL,
  "author_id" TEXT NOT NULL,
  "position" INTEGER NOT NULL,
  CONSTRAINT "article_authors_pkey" PRIMARY KEY ("article_id", "author_id")
);
CREATE INDEX "article_authors_author_id_idx" ON "article_authors"("author_id");
ALTER TABLE "article_authors" ADD CONSTRAINT "article_authors_article_id_fkey"
  FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "article_authors" ADD CONSTRAINT "article_authors_author_id_fkey"
  FOREIGN KEY ("author_id") REFERENCES "authors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ── editors ─────────────────────────────────────────────────────────────

CREATE TABLE "editors" (
  "id" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "role" "EditorRole" NOT NULL,
  "publication_id" TEXT NOT NULL,
  "institution" TEXT,
  "country" TEXT,
  "bio" TEXT,
  "profile_image" TEXT,
  "orcid" TEXT,
  "research_interests" TEXT[],
  "display_order" INTEGER NOT NULL,
  "status" "EditorStatus" NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "editors_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "editors_slug_key" ON "editors"("slug");
CREATE INDEX "editors_publication_id_idx" ON "editors"("publication_id");
ALTER TABLE "editors" ADD CONSTRAINT "editors_publication_id_fkey"
  FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── reviewers (PRIVATE — never exposed publicly) ───────────────────────

CREATE TABLE "reviewers" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "institution" TEXT,
  "country" TEXT,
  "expertise" TEXT[],
  "status" "ReviewerStatus" NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "reviewers_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "reviewers_email_key" ON "reviewers"("email");

-- ── reviews (PRIVATE — never exposed publicly) ─────────────────────────

CREATE TABLE "reviews" (
  "id" TEXT NOT NULL,
  "manuscript_id" TEXT NOT NULL,
  "reviewer_id" TEXT NOT NULL,
  "recommendation" "ReviewRecommendation",
  "comments" TEXT,
  "submitted_at" TIMESTAMP(3),
  "status" TEXT NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "reviews_manuscript_id_idx" ON "reviews"("manuscript_id");
CREATE INDEX "reviews_reviewer_id_idx" ON "reviews"("reviewer_id");
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_manuscript_id_fkey"
  FOREIGN KEY ("manuscript_id") REFERENCES "articles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_reviewer_id_fkey"
  FOREIGN KEY ("reviewer_id") REFERENCES "reviewers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── indexing_services ───────────────────────────────────────────────────

CREATE TABLE "indexing_services" (
  "id" TEXT NOT NULL,
  "publication_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "url" TEXT,
  "logo" TEXT,
  "status" "IndexingStatus" NOT NULL,
  "display_order" INTEGER NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "indexing_services_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "indexing_services_publication_id_idx" ON "indexing_services"("publication_id");
ALTER TABLE "indexing_services" ADD CONSTRAINT "indexing_services_publication_id_fkey"
  FOREIGN KEY ("publication_id") REFERENCES "publications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ── contact_messages ────────────────────────────────────────────────────

CREATE TABLE "contact_messages" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "subject" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "category" TEXT,
  "status" "ContactMessageStatus" NOT NULL DEFAULT 'new',
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "contact_messages_pkey" PRIMARY KEY ("id")
);

-- ── users ───────────────────────────────────────────────────────────────

CREATE TABLE "users" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "role" "UserRole" NOT NULL,
  "reviewer_id" TEXT,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_reviewer_id_key" ON "users"("reviewer_id");
ALTER TABLE "users" ADD CONSTRAINT "users_reviewer_id_fkey"
  FOREIGN KEY ("reviewer_id") REFERENCES "reviewers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ── password_reset_tokens ───────────────────────────────────────────────

CREATE TABLE "password_reset_tokens" (
  "id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "token_hash" TEXT NOT NULL,
  "expires_at" TIMESTAMP(3) NOT NULL,
  "used_at" TIMESTAMP(3),
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "password_reset_tokens_token_hash_key" ON "password_reset_tokens"("token_hash");
CREATE INDEX "password_reset_tokens_user_id_idx" ON "password_reset_tokens"("user_id");
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Note: the `session` table (used by connect-pg-simple for server-side
-- session storage, see src/config/session.ts) is intentionally NOT
-- created here — connect-pg-simple creates it automatically on first
-- connection (createTableIfMissing: true). It has no Prisma model.
